fix = true
show-fixes = true

# enable later: "C90", "PTH", "TCH", "RET", "ANN"
select = ["E", "F", "W", "I", "N", "D", "UP", "PL", "Q", "SIM", "TID", "ARG"]
ignore = ["PLR2004", "N818"]
extend-exclude = ["app_vars.py"]
unfixable = ["F841"]
line-length = 100
target-version = "py311"

[flake8-annotations]
allow-star-arg-any = true
suppress-dummy-args = true

[flake8-builtins]
builtins-ignorelist = ["id"]

[pydocstyle]
# Use Google-style docstrings.
convention = "pep257"

[pylint]
max-branches=25
max-returns=15
max-args=10
max-statements=50
