# Descriptions for Music Assistant custom services

play_media:
  target:
    entity:
      domain: media_player
      integration: mass
      supported_features:
        - media_player.MediaPlayerEntityFeature.PLAY_MEDIA
  fields:
    media_id:
      required: true
      example: "spotify://playlist/aabbccddeeff"
      selector:
        object:
    media_type:
      required: false
      example: "playlist"
      selector:
        select:
          options:
            - artist
            - album
            - playlist
            - track
            - radio
    enqueue:
      filter:
        supported_features:
          - media_player.MediaPlayerEntityFeature.MEDIA_ENQUEUE
      required: false
      selector:
        select:
          options:
            - "play"
            - "replace"
            - "next"
            - "replace_next"
            - "add"
          translation_key: enqueue
    announce:
      filter:
        supported_features:
          - media_player.MediaPlayerEntityFeature.MEDIA_ANNOUNCE
      required: false
      example: "true"
      selector:
        boolean:
    radio_mode:
      required: false
      advanced: true
      selector:
        boolean:


search:
  fields:
    query:
      required: true
      example: "Queen - Innuendo"
      selector:
        text:
    media_type:
      required: false
      example: "playlist"
      selector:
        select:
          multiple: true
          options:
            - artist
            - album
            - playlist
            - track
            - radio
    limit:
      required: false
      example: 25
      default: 25
      selector:
        number:
          min: 1
          max: 100
          step: 1
