name: Report a Bug in Music Assistant
description: Report an issue with Music Assistant.
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!
        For questions read our [FAQ section][fq] or visit our community on [Discord][cf].
        If you have a feature or enhancement request, please enter them in our discussions section [feature request][fr]

        [fq]: https://github.com/music-assistant/hass-music-assistant/discussions/categories/q-a-faq
        [cf]: https://discord.com/channels/753947050995089438/753947050995089442
        [fr]: https://github.com/music-assistant/hass-music-assistant/discussions/categories/feature-requests-and-ideas
  - type: input
    id: version_MA
    validations:
      required: true
    attributes:
      label: What version of Music Assistant has the issue?
      placeholder: 2022.x.y
      description: >
        Can be found in: MA SETTINIGS>>CORE
        For example: 2.0.0b94
  - type: input
    id: version_integration
    validations:
      required: false
    attributes:
      label: What version of the Home Assistant Integration have you got installed?
      placeholder: 2022.x.y
      description: >
        Can be found in: HACS>>INTEGRATIONS>>MUSIC ASSISTANT
        For example: 2024.1.0
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?
      description: |
        You must answer yes to this
      options:
        - Yes
        - No
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: |
        Please give a clear and concise description of the issue you are experiencing here,
        to communicate to the maintainers. Tell us what you were trying to do and what happened.
  - type: textarea
    validations:
      required: true
    attributes:
      label: How to reproduce
      description: |
        Describe the least amount of steps possible to reproduce your error
  - type: textarea
    validations:
      required: true
    attributes:
      label: Music Providers
      description: |
        List the music providers that you have tried which result in the problem. Also list the music providers you have tried that don't show the problem
  - type: textarea
    validations:
      required: true
    attributes:
      label: Player Providers
      description: |
        List the player providers that you have tried which result in the problem. Also list the player providers you have tried that don't show the problem. Also indicate if you are trying to play to grouped players.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. Use the field below. Please do NOT use debug logging unless asked to do so
  - type: textarea
    attributes:
      label: Additional information
      description: |
        If you have any additional information for us. Use the field below. Include how the playback is being instigated if that makes a difference (ie. via the UI or via HA service call), what you have tried from the troubleshooting FAQ and detail what is working so it is clear you have narrowed down the problem. Additionally, if you aren't running HAOS or have an unusual network setup provide details about that.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version_HA
    validations:
      required: true
    attributes:
      label: What version of Home Assistant Core are your running
      placeholder: 2024.2.0
      description: |
        Can be found in: [Settings -> About](https://my.home-assistant.io/redirect/info/).
        For example: 2024.2.0
        [![Open your Home Assistant instance and show your Home Assistant version information.](https://my.home-assistant.io/badges/info.svg)](https://my.home-assistant.io/redirect/info/)
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you running?
      description: |
        Can be found in: [Settings -> About](https://my.home-assistant.io/redirect/info/).

        [![Open your Home Assistant instance and show your Home Assistant version information.](https://my.home-assistant.io/badges/info.svg)](https://my.home-assistant.io/redirect/info/)
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Supervised
        - Home Assistant Core
  - type: dropdown
    validations:
      required: true
    attributes:
      label: On what type of hardware are you running?
      description: |
        Can be found in: [Settings -> System -> Hardware](https://my.home-assistant.io/redirect/hardware/).

        [![Open your Home Assistant instance and show your hardware information.](https://my.home-assistant.io/badges/hardware.svg)](https://my.home-assistant.io/redirect/hardware/)
      options:
        - Raspberry Pi
        - ODROID
        - ASUS Tinkerboard
        - Generic x86-64 (e.g. Intel NUC)
        - Windows
        - macOS
        - Linux
        - Alternative
