name: Report a Bug in Music Assistant
description: Report an issue with Music Assistant.
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only! Read this for what you MUST include [Troubleshooting][ft]
        For questions read our [FAQ section][fq] or visit our community on [Discord][cf].
        If you have a feature or enhancement request, please enter them in our discussions section [feature request][fr]

        [fq]: https://github.com/orgs/music-assistant/discussions/categories/q-a
        [cf]: https://discord.com/channels/753947050995089438/753947050995089442
        [fr]: https://github.com/orgs/music-assistant/discussions/categories/feature-requests-and-ideas
        [ft]: https://music-assistant.io/faq/troubleshooting/

  - type: input
    id: version_MA
    validations:
      required: true
    attributes:
      label: What version of Music Assistant has the issue?
      placeholder: 2.5.5
      description: >
        Can be found in: MA SETTINGS>>CORE
        For example: 2.4.0b20
  - type: dropdown
    validations:
      required: true
    attributes:
      label: How is the MA server installed?
      description: |
        Can be found in: [Settings -> About](https://my.home-assistant.io/redirect/info/).

        [![Open your Home Assistant instance and show your Home Assistant version information.](https://my.home-assistant.io/badges/info.svg)](https://my.home-assistant.io/redirect/info/)
      options:
        - Home Assistant OS Addon
        - Docker Container
        - Other - Please do not select this as support is only available for the above two options
  - type: checkboxes
    validations:
      required: true
    attributes:
      label: Carefully read the Troubleshooting FAQ and confirm that:
      description: |
        If you tick a box that you haven't done, and it is applicable, then clearly state that and explain why in the report
      options:
        - label: "I have examined the logs and tried to resolve this issue"
          required: true
        - label: "I have fixed any errors in the logs that relate to tags"
          required: true
        - label: "I am not running MA across a VPN, VLAN, subnet, behind a firewall, or using local SSL or have any other complex network setup"
          required: true
        - label: "I have disabled tool such as AdGuard, Pi-hole or pfSense and retested"
          required: true
        - label: "I have checked my network setup to ensure mDNS/multicast is not being blocked"
          required: true
        - label: "If using HA, I have confirmed the internal URL is set correctly"
          required: true
        - label: "I have tried a wired connection for issues related to interrupted or poor playback quality"
          required: true
        - label: "If the problem relates to a device then I have checked the device settings"
          required: true
        - label: "If it is a frontend issue, I have tried a different widely used browser"
          required: true
        - label: "I have reviewed the applicable [player](https://www.music-assistant.io/player-support/) or [music provider](https://www.music-assistant.io/music-providers/) documentation"
          required: true
        - label: "For voice problems, I have sought help elsewhere before returning here"
          required: true
        - label: "For playback problems, I have recycled power to the physical device"
          required: true
        - label: "I have tried restarting MA and rebooting the host"
          required: true
 - type: checkboxes
    validations:
      required: true
    attributes:
      label: Have you reviewed the [Open](https://github.com/music-assistant/support/issues) and [Closed](https://github.com/music-assistant/support/issues?q=is%3Aissue%20state%3Aclosed) Issues and [Discussions](https://github.com/orgs/music-assistant/discussions) to resolve this yourself?
      options:
        - label: "Yes"
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: |
        Please give a clear and concise description of the issue you are experiencing here,
        to communicate to the maintainers. Tell us what you were trying to do and what happened. Detail what you have tried from the troubleshooting page in the docs that hasn't helped.
  - type: textarea
    validations:
      required: true
    attributes:
      label: How to reproduce
      description: |
        Describe the least amount of steps possible to reproduce your error
  - type: textarea
    validations:
      required: true
    attributes:
      label: Music Providers
      description: |
        List the music providers that you have tried which result in the problem. ALSO list the music providers you have tried that don't show the problem
  - type: textarea
    validations:
      required: true
    attributes:
      label: Player Providers
      description: |
        List the player providers that you have tried which result in the problem. ALSO list the player providers you have tried that don't show the problem. Also indicate if you are trying to play to grouped players.
  - type: textarea
    validations:
      required: true
    id: logs
    attributes:
      label: Full log output
      placeholder: DO NOT PASTE the log here. ATTACH IT.
      description: |
        Please DOWNLOAD then DRAG and DROP the full log output from MA SETTINGS>>CORE into the field below. Do NOT use Verbose logging unless asked to do so.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Additional information
      placeholder: For Audiobookshelf include broken book ASINs here
      description: |
        Supply additional information requested which is not captured above, specifically the information requested in the troubleshooting page of the docs. Include how the playback is being instigated if that makes a difference (ie. via the UI or via HA service call), what you have tried from the troubleshooting FAQ and detail what is working so it is clear you have narrowed down the problem. Additionally, if you aren't running HAOS or have an unusual network setup provide details about that.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version_HA
    validations:
      required: true
    attributes:
      label: What version of Home Assistant Core (if used) are your running
      placeholder: 2025.8.0
      description: |
        Can be found in: [Settings -> About](https://my.home-assistant.io/redirect/info/).
        For example: 2025.8.0
        [![Open your Home Assistant instance and show your Home Assistant version information.](https://my.home-assistant.io/badges/info.svg)](https://my.home-assistant.io/redirect/info/)
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you running?
      description: |
        Can be found in: [Settings -> About](https://my.home-assistant.io/redirect/info/).

        [![Open your Home Assistant instance and show your Home Assistant version information.](https://my.home-assistant.io/badges/info.svg)](https://my.home-assistant.io/redirect/info/)
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Other - Please do not select this as support is only available for the above two options
  - type: dropdown
    validations:
      required: true
    attributes:
      label: On what type of hardware are you running?
      description: |
        Can be found in: [Settings -> System -> Hardware](https://my.home-assistant.io/redirect/hardware/).

        [![Open your Home Assistant instance and show your hardware information.](https://my.home-assistant.io/badges/hardware.svg)](https://my.home-assistant.io/redirect/hardware/)
      options:
        - Raspberry Pi
        - ODROID
        - ASUS Tinkerboard
        - Generic x86-64 (e.g. Intel NUC)
        - Windows
        - macOS
        - Linux
        - Alternative
  - type: checkboxes
    validations:
      required: true
    attributes:
      label: Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot
      description: |
        Failing to provide all the requested information slows down the resolution process and creates unnecessary work for those trying to help.
      options:
        - label: "Yes"
          required: true
