name: 🌍 Translation contribution
description: Offer to help translate Music Assistant into a new language.
labels: ["triage", "translation"]
assignees:
  - jozefKruszynski
body:
  - type: markdown
    attributes:
      value: |
        This form is for offering to contribute a translation.
        Please read how the process works in [this discussion][lc] first.

        [lc]: https://github.com/orgs/music-assistant/discussions/1216
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Which project is the translation for?
      options:
        - Frontend (web app)
        - Mobile app
  - type: input
    id: new_language
    validations:
      required: true
    attributes:
      label: New language
      placeholder: Klingon
      description: >
        The language you'd like to contribute.
  - type: textarea
    id: additional_remarks
    validations:
      required: false
    attributes:
      label: Additional remarks
      description: |
        Anything else you'd like to add (optional).
