name: Validate with hassfest

on:
  push:
    paths:
      - '**.py'
      - 'requirements_dev.txt'
  pull_request:
    paths:
      - '**.py'
      - 'requirements_dev.txt'
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: home-assistant/actions/hassfest@master
