name: Lint Vue frontend
on:
  push:
    paths:
      - 'custom_components/mass/frontend/*'
  pull_request:
    paths:
      - 'custom_components/mass/frontend/*'
  workflow_dispatch:


defaults:
  run:
    working-directory: custom_components/mass/frontend

env:
  NODE_VERSION: "17.x" # set this to the node version to use

jobs:
  lint_vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install and lint
        run: |
          npm install
          npm run lint
