name: Publish release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.tag }}

    steps:
      - uses: actions/checkout@v3.5.3
      - name: Get tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.10"

      - name: build frontend
        working-directory: custom_components/mass/frontend/
        run: |
          npm install
          npm run build

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: Patch manifest and zip
        run: |
          sed -i 's/0.0.0/${{ steps.vars.outputs.tag }}/' custom_components/mass/manifest.json

          cd custom_components/mass/
          zip ../../mass.zip ./* translations/* frontend/dist/* -x '.*'

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./mass.zip
          asset_name: mass.zip
          tag: ${{ github.ref }}
