name: Publish release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: build frontend
        working-directory: custom_components/mass/frontend/
        run: |
          npm install
          npm run build

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: Patch manifest and zip
        run: |
          sed -i 's/v0.0.0/${{ steps.version.outputs.version }}/' custom_components/mass/manifest.json

          cd custom_components/mass/
          zip ../../mass.zip ./* translations/* frontend/dist/* -x '.*'

      - uses: gacts/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ./mass.zip
          type: application/zip