name: HACS Validate

on:
  push:
    paths:
      - '**.py'
      - 'requirements_dev.txt'
  pull_request:
    paths:
      - '**.py'
      - 'requirements_dev.txt'
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          # brands is disabled awaiting the PR with icon to be merged
          # requirements is disabled because custom-wheels-builder repo is postponed
          ignore: brands requirements
